apiVersion: v1
kind: Service
metadata:
  name: azure-devops-agent
  labels:
    app: azure-devops-agent
spec:
  clusterIP: None
  selector:
    app: azure-devops-agent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azure-devops-agent
spec:
  selector:
    matchLabels:
      app: azure-devops-agent
  serviceName: "azure-devops-agent"
  replicas: 4
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-devops-agent
        image: registryacrdgzib6ds.azurecr.io/azure-devops-agent:latest
        env:
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: azp-variables
              key: azp-url        
        - name: AZP_USER
          valueFrom:
            secretKeyRef:
              name: azp-variables
              key: azp-user        
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azp-variables
              key: azp-token        


         