apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.97
    path: /export/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      type: nfs
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    run: custom-nfs-test
  name: custom-nfs-test
spec:
  replicas: 1
  serviceName: ubuntu
  selector:
    matchLabels:
      run: custom-nfs-test
  template:
    metadata:
      labels:
        run: custom-nfs-test
    spec:
      containers:
      - args:
        - bash
        image: ubuntu:19.04
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: IfNotPresent
        name: custom-nfs-test
        resources: {}
        volumeMounts:
        - mountPath: /mnt/customnfs
          name: volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: data
